title:             Jean Fan Is A Fan Of Genes
email:             jeanfan@fas.harvard.edu
description:       reflections on science and academia
author:            Jean Fan
baseurl:           "/"
url:               "http://jean.fan"
logo:		   "img/logo.png"

# Social Profiles
twitter_username:  JEFworks
github_username:   JEFworks
instagram_username: JEFworks

# Build settings
markdown:          kramdown
highlighter:       rouge
paginate:          5
paginate_path:     "/posts/page:num/"

plugins:
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore